export const state = {
  apiBase: localStorage.getItem("lightflow.apiBase") || "http://127.0.0.1:5174",
  nodes: [],
  categories: [],
  executorCatalog: null,
  executors: [],
  modelCatalog: null,
  models: [],
  runCatalog: null,
  runs: [],
  artifacts: [],
  patches: [],
  loopReport: null,
  loopError: "",
  loopChanges: null,
  loopChangesError: "",
  projectWorkspaces: null,
  projectWorkspacesError: "",
  publishCatalog: null,
  publishCatalogError: "",
  releaseReport: null,
  releaseError: "",
  workflows: {},
  workflowErrors: {},
  workflowLoading: new Set(),
  plans: {},
  planErrors: {},
  planLoading: new Set(),
  loopReports: {},
  loopErrors: {},
  loopLoading: new Set(),
  selectedLoopRequireReplay: false,
  publishChecks: {},
  publishErrors: {},
  publishLoading: new Set(),
  releaseReports: {},
  releaseErrors: {},
  releaseLoading: new Set(),
  selectedNodeId: null,
  selectedRunId: null,
  selectedPatchName: "",
  modelFilters: {
    workflow: "",
    status: "all",
  },
  runFilters: {
    workflow: "",
    status: "",
    limit: "100",
  },
  artifactFilters: {
    run: "",
    workflow: "",
    kind: "",
    limit: "100",
  },
  runPatchDraft: "",
  patchDraft: '{\n  "nodes": {}\n}',
};

export const els = {
  statusText: document.querySelector("#statusText"),
  connectionForm: document.querySelector("#connectionForm"),
  apiBase: document.querySelector("#apiBase"),
  nodeFilter: document.querySelector("#nodeFilter"),
  categoryFilter: document.querySelector("#categoryFilter"),
  nodeList: document.querySelector("#nodeList"),
  nodeDetail: document.querySelector("#nodeDetail"),
  executorList: document.querySelector("#executorList"),
  modelFilterForm: document.querySelector("#modelFilterForm"),
  modelWorkflowFilter: document.querySelector("#modelWorkflowFilter"),
  modelStatusFilter: document.querySelector("#modelStatusFilter"),
  modelFilterReset: document.querySelector("#modelFilterReset"),
  modelList: document.querySelector("#modelList"),
  runFilterForm: document.querySelector("#runFilterForm"),
  runWorkflowFilter: document.querySelector("#runWorkflowFilter"),
  runStatusFilter: document.querySelector("#runStatusFilter"),
  runLimitFilter: document.querySelector("#runLimitFilter"),
  runFilterReset: document.querySelector("#runFilterReset"),
  runList: document.querySelector("#runList"),
  runDetail: document.querySelector("#runDetail"),
  patchList: document.querySelector("#patchList"),
  patchDetail: document.querySelector("#patchDetail"),
  artifactFilterForm: document.querySelector("#artifactFilterForm"),
  artifactRunFilter: document.querySelector("#artifactRunFilter"),
  artifactWorkflowFilter: document.querySelector("#artifactWorkflowFilter"),
  artifactKindFilter: document.querySelector("#artifactKindFilter"),
  artifactLimitFilter: document.querySelector("#artifactLimitFilter"),
  artifactFilterReset: document.querySelector("#artifactFilterReset"),
  artifactList: document.querySelector("#artifactList"),
  loopDetail: document.querySelector("#loopDetail"),
  emptyTemplate: document.querySelector("#emptyTemplate"),
};
